[package]
name = "pf2e_terrain_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
once_cell = "1.16.0"
image = "0.24.5"
chrono = "0.4.23"

[dependencies.sdl2]
version = "0.35"
features = ["image", "gfx", "bundled"]